### ISSUE TITLE
SyncAll exited with fatal Win32 error: 8440 (0x20f8)

### ISSUE THREAD

**Issue by Betep0k** [Orange-Cyberdefense/GOAD#140]
Hey! Ansible fails with next error during the installation:

```
TASK [groups_domains : synchronizes all domains] **********************************************************************************************************************************************************
changed: [dc03]
fatal: [dc02]: FAILED! => {"changed": true, "cmd": "repadmin /syncall /Ade", "delta": "0:00:00.487731", "end": "2023-11-12 18:14:13.730175", "msg": "non-zero return code", "rc": 1, "start": "2023-11-12 18:14:13.242443", "stderr": "", "stderr_lines": [], "stdout": "Syncing all NC's held on winterfell.\r\r\nSyncing partition: DC=north,DC=sevenkingdoms,DC=local\r\r\nCALLBACK MESSAGE: Error contacting server CN=NTDS Settings,CN=WINTERFELL,CN=Servers,CN=Default-First-Site-Name,CN=Sites,CN=Configuration,DC=sevenkingdoms,DC=local (network error): 1722 (0x6ba):\r\r\n    The RPC server is unavailable.\r\r\n\r\r\nSyncAll exited with fatal Win32 error: 8440 (0x20f8):\r\r\n    The naming context specified for this replication operation is invalid.\r\r\n", "stdout_lines": ["Syncing all NC's held on winterfell.", "", "Syncing partition: DC=north,DC=sevenkingdoms,DC=local", "", "CALLBACK MESSAGE: Error contacting server CN=NTDS Settings,CN=WINTERFELL,CN=Servers,CN=Default-First-Site-Name,CN=Sites,CN=Configuration,DC=sevenkingdoms,DC=local (network error): 1722 (0x6ba):", "", "    The RPC server is unavailable.", "", "", "", "SyncAll exited with fatal Win32 error: 8440 (0x20f8):", "", "    The naming context specified for this replication operation is invalid.", ""]}
changed: [dc01]
```

No other errors before this one.

GOAD: Main branch, 4cdbab4 commit
VMware VM with clean ubuntu 20.04 with last updates
Virtualbox: 6.1.38_Ubuntu r153438
Docker: 24.0.7
Vagrant; 2.4.0

**Comment by necx512** [comment]
I had the same issue with:
- Debian 12 (recently installed)
- python3 (3.11.2)
- ansible-core 2.12.6
- Vagrant (2.3.8.dev)
- VirtualBox 7
- IPv6 disabled on my host

I suspect that this is a DNS issue. Especially, I observed that, for some reasons, the  command 'Install-ADDSDomain' in 'ansible/roles/child_domain/tasks/main.yml' adds 127.0.0.1 and 10.0.2.3 as DNS servers on card called 'Ethernet' and I don't understand why.

Here is how i solved it.  **Note that it is just my personal observations. Some of the described step could be useless. I'm still to understand why this issue is happening** If you have another solution, I will be glad to read it.

1/ First, connect on DC02 as the user called vagrant. Then run cmd.exe as administrator (right click -> run as administrator). Then execute `repadmin /syncall /Ade` to reproduce the error
2/ Secondly, disable all IPv6 for all cards for DC01, DC02, DC03.
3/ For the IPv4 properties of network card called "Ethernet" (the one that has not a fixed IP), select "obtain DNS server address automatically". Do it for DC01,DC02 and DC03 (Here, I'm wondering if doing it only on DC02 could work)
4/ On DC01, DC02 and DC03, flush the DNS cache with `ipconfig /flushdns`
5/ Waiting few minutes
6/ retry step 1
7/ `./goad.sh -t install -l GOAD -p virtualbox -m local`

**Comment by Betep0k** [comment]
Thanks @necx512! Looks like your trick is working :)

**Comment by necx512** [comment]
After new tests I think that disabling IPv6 and DNS is not required.
Waiting a while seems to be the key to solve this issue.

1/ ./goad.sh -t install -l GOAD -p virtualbox -m local
2/ observe your error
3/ wait few minutes while all machines are up
4/ retry : ./goad.sh -t install -l GOAD -p virtualbox -m local

**Comment by ret2src** [comment]
Waiting for a few minutes solved the issue for me as well. Arch Linux, Vagrant 2.4.1 git, VirtualBox 7.0.12.

**Comment by Mayfly277** [comment]
Windows..., sometimes just wait and retry solve all ^^

**Comment by Kerjha** [comment]
This error has occurred to me again. The exact same one.
I am running this on:
- the main branch, 992307adf944b934a3b76a2f56a637104c54b805
- proxmox (pve)
- Python 3.14.4
- ansible 2.20.1-1

I have tried waiting for 20 minutes, as well as disabling IPv6 and changing up my dns.
I try to run the script and it gives me this error every time I try to run it, but I don't seem to be making any progress.
Did anyone discover any other fixes besides waiting?

Edit: I managed to fix it, by changing the post reboot delay in /GOAD/ansible/roles/groups_domains/tasks/main.yml to 300 instead of 100, so that the NTDS service actually has enough time to start.
