### ISSUE TITLE
Terraform plugin crash with proxmox >= 8.1.X [Solution Here]

### ISSUE THREAD

**Issue by aliafenice** [Orange-Cyberdefense/GOAD#171]
Hi at all,

The terraform run crash with plugin error.

The fix for now is the same

raplace this in the main.tf

```
terraform {
  required_providers {
    proxmox = {
      source = "telmate/proxmox"
      version = ">=1.0.0"
    }
  }
}

with 

terraform {
  required_providers {
    proxmox = {
      source = "TheGameProfi/proxmox"
      version = ">=1.0.0"
    }
  }
}
```

and do a rm -rf .terraform

after that a run on terraform init e redo a build.

Cheers

Happy Holidays

**Comment by burnbrian** [comment]
Thank you for posting. I was having the same issue on '8.1.3'. For anyone interested the issue is discussed [here](https://github.com/Telmate/terraform-provider-proxmox/issues/869). Two alternate providers are recommended on the linked issue:

* [TheGameProfi](https://github.com/TheGameProfi/terraform-provider-proxmox)
* [bpg](https://github.com/bpg/terraform-provider-proxmox)

**Comment by jamu85** [comment]
I would recommend utilizing the bpg provider as it's much more stable and has more options than the telmate provider. I can make a PR with the necessary changes if anyone is interested.

**Comment by Mayfly277** [comment]
all the proxmox terraform receipe were moved to bpg :)
