### ISSUE TITLE
Problem with bloodhound.py through a socks5 using proxychains

### ISSUE THREAD

**Issue by belveruski** [Orange-Cyberdefense/GOAD#78]
Hi, 
I have a strange problem when i try to use `bloodhound.py`  to collect information from the domain sevenkingdoms.local.

During the process, bloodhound.py try to authenticate to the LDAP server (main DC=kingslanding.sevenkingdoms.local) by contacting the ip address 10.0.2.15 on port 389 but it should be the ip address 192.168.56.10.

Details of the command and error:

```bash
 proxychains bloodhound.py -v --zip -c All -d sevenkingdoms.local -u administrator -p '8dCT-DJjgScp' --dns-tcp -ns 192.168.56.10 -dc kingslanding.sevenkingdoms.local
``` 
Error
```text
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/lib/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.16-git-9-g060801d
DEBUG: Authentication: username/password
DEBUG: Resolved collection methods: session, trusts, rdp, objectprops, dcom, group, container, localadmin, acl, psremote
DEBUG: Using DNS to retrieve domain information
DEBUG: Querying domain controller information from DNS
DEBUG: Using domain hint: sevenkingdoms.local
[proxychains] Strict chain  ...  127.0.0.1:1090  ...  192.168.56.10:53  ...  OK
INFO: Found AD domain: sevenkingdoms.local
DEBUG: Found primary DC: kingslanding.sevenkingdoms.local
[proxychains] Strict chain  ...  127.0.0.1:1090  ...  192.168.56.10:53  ...  OK
DEBUG: Found Global Catalog server: kingslanding.sevenkingdoms.local
DEBUG: Found Global Catalog server: winterfell.north.sevenkingdoms.local
DEBUG: Using LDAP server: kingslanding.sevenkingdoms.local
DEBUG: Using base DN: DC=sevenkingdoms,DC=local
INFO: Connecting to LDAP server: kingslanding.sevenkingdoms.local
[proxychains] Strict chain  ...  127.0.0.1:1090  ...  192.168.56.10:53  ...  OK
DEBUG: Authenticating to LDAP server
**[proxychains] Strict chain  ...  127.0.0.1:1090  ...  10.0.2.15:389 <--socket error or timeout!**
Traceback (most recent call last):
  File "/opt/tools/BloodHound.py/bloodhound.py", line 5, in <module>
    bloodhound.main()
  File "/opt/tools/BloodHound.py/bloodhound/__init__.py", line 317, in main
    bloodhound.run(collect=collect,
  File "/opt/tools/BloodHound.py/bloodhound/__init__.py", line 79, in run
    self.pdc.prefetch_info('objectprops' in collect, 'acl' in collect, cache_computers=do_computer_enum)
  File "/opt/tools/BloodHound.py/bloodhound/ad/domain.py", line 516, in prefetch_info
    self.get_objecttype()
  File "/opt/tools/BloodHound.py/bloodhound/ad/domain.py", line 241, in get_objecttype
    self.ldap_connect()
  File "/opt/tools/BloodHound.py/bloodhound/ad/domain.py", line 70, in ldap_connect
    ldap = self.ad.auth.getLDAPConnection(hostname=ip,
  File "/opt/tools/BloodHound.py/bloodhound/ad/authentication.py", line 78, in getLDAPConnection
    if not conn.bind():
  File "/usr/local/lib/python3.9/dist-packages/ldap3/core/connection.py", line 589, in bind
    self.open(read_server_info=False)
  File "/usr/local/lib/python3.9/dist-packages/ldap3/strategy/sync.py", line 57, in open
    BaseStrategy.open(self, reset_usage, read_server_info)
  File "/usr/local/lib/python3.9/dist-packages/ldap3/strategy/base.py", line 146, in open
    raise exception_history[0][0]
ldap3.core.exceptions.LDAPSocketOpenError: socket connection error while opening: [Errno 111] Connection refused

```

After multiple tests, same problem with bloodhound.py without socks using this command:
```bash
bloodhound.py -v --zip -c All -d north.sevenkingdoms.local -u brandon.stark -p iseedeadpeople -dc winterfell.north.sevenkingdoms.local -ns 192.168.56.10
```
During the authentication to the LDAP server the script try to connect to contact 10.0.2.15 on port 389 (second interface for vagrant).

Thank you in advance for your help and your work.

**Comment by KenjiEndo15** [comment]
The issue is related to NIC teaming & multi-homed networks. 
Vagrant has to use 2 network interfaces (which is really annoying).
I tried to give a solution to Mayfly to avoid that. The thing is, my previous solution didn't work in some cases.

So, I played around in a lab for a while, trying to solve this. I came up with new "solutions" that can be added to GOAD.
I can guarantee it works everytime to avoid 2 network interfaces, and therefore mitigate any issues with tools like BloodHound.py. However, I didn't have any experience with edge cases (which is why I'm always reticent to propose pull requests).

Anyways, here are the solutions I found.

### Miscellaneous
On my docker container (Kali Linux), I had to modify not only the `/etc/hosts` file, but also the `/etc/resolv.conf` file to reflect the informations about GOAD's domains.

As an example:
```
# /etc/hosts
192.168.56.10 hacker.local
```

```
# /etc/resolv.conf
nameserver 192.168.56.10
domain hacker.local
```

### Long solution

#### Host configuration

When setting up a **domain controller** - You have to disable the registration of the Ethernet interface (NAT) in the DNS configuration.

```
- name: disable the registration of the Ethernet interface (NAT address) in DNS
  ansible.windows.win_shell:
    Get-NetAdapter Ethernet | Set-DNSClient -RegisterThisConnectionsAddress $False
```

When setting up **servers** - You have to prioritize the Ethernet 2 interface (local) as the default for routing. Otherwise, from a Windows Servers, the route would be messed up when trying to contact the domain and its computers.

```
- name: prioritize the Ethernet 2 interface (local) as the default for routing
  ansible.windows.win_shell:
    Set-NetIPInterface -InterfaceAlias "Ethernet 2" -InterfaceMetric 10
```

#### ADDS (Active Directory Domain Services) configuration
When setting up a **domain controller** - You have to enable the Ethernet 2 interface (local) only, for DNS client requests.

```
- name: enable only the Ethernet 2 interface (local) for DNS client requests
  ansible.windows.win_shell:
    dnscmd dc01 /resetlistenaddresses "{{ hostvars['dc01']['host_ip'] }}"
```

### Short solution
This solution sucks because the configurations come back again after some time.

In a **domain controller**:

```
- name: disable NIC registration for the ethernet (unrelated to the private network)
  ansible.windows.win_shell:
    get-netadapter ethernet | set-dnsclient -registerthisconnectionsaddress $false

- name: force the change
  ansible.windows.win_shell:
    ipconfig /renew ethernet
```

If you want to test your Bloodhound.py directly, just log into a domain controller and type the Powershell commands listed above. On your Linux host you should see only one interface, the local one (192.168.56.XY).

Hope this helps.

### None of the solutions mentionned were tested with multiple domains/DNS.

**Comment by Mayfly277** [comment]
Thx a lot for this answer i will do some test with your workaround, this seems very interesting !

**Comment by alexbeam** [comment]
In the "Long solution" in which files should I add the ansible script entries before building the environment?

**Comment by KenjiEndo15** [comment]
> In the "Long solution" in which files should I add the ansible script entries before building the environment?

I assume (I only tested in my lab) you have to modify the following configuration files.

### Host configuration
**File 1**: `GOAD/ansible/roles/domain_controller/tasks/main.yml`
Replace the line 1 to 2 with the following code:

```
- name: disable the registration of the Ethernet interface (NAT address) in DNS
  ansible.windows.win_shell:
    Get-NetAdapter Ethernet | Set-DNSClient -RegisterThisConnectionsAddress $False
```

**File 2**: `GOAD/ansible/roles/member_server/tasks/main.yml`
Starting from line 1 (before anything else in the file), add the following code:

```
- name: prioritize the Ethernet 2 interface (local) as the default for routing
  ansible.windows.win_shell:
    Set-NetIPInterface -InterfaceAlias "Ethernet 2" -InterfaceMetric 10
```

### ADDS (Active Directory Domain Services) configuration
**File 1**: `GOAD/ansible/roles/domain_controller/tasks/main.yml`
From line 52, add the following code:

```
- name: enable only the Ethernet 2 interface (local) for DNS client requests
  ansible.windows.win_shell:
    dnscmd dc01 /resetlistenaddresses "{{ hostvars['dc01']['host_ip'] }}"
```

GOAD has more functionalities than the lab I created to test my stuff. I wouldn't be surprised if the code I proposed would fail the build, it'll need some debugging.

**Comment by Mayfly277** [comment]
@KenjiEndo15  thanks again for your advice, i used it on the last push and it seems to work quite well !
