### ISSUE TITLE
Trouble SRV02 to join the NORTH.SEVENKINGDOMS.LOCAL domain

### ISSUE THREAD

**Issue by OtterHacker** [Orange-Cyberdefense/GOAD#97]
Hello !
Thank's for the work ! :)

I'm starting to get errors when SRV02 join the NORTH.SEVENKINGDOMS.LOCAL domain :
``` 
domain controller the specified network name is no longer available
```
Disabling Windows Defender on SRV02 and DC02 when joining the domain seems to fix the problem but I don't know enough Ansible to make the modification in the code.

Don't know if it's an isolated case or due to Windows patch tho.

**Comment by NeffIsBack** [comment]
Okay super weird behaviour:

### First Run
On the first run i am getting the error:
`fatal: [srv02]: FAILED! => {"changed": true, "msg": "failed to join domain: Computer 'castelblack' failed to join domain 'north.sevenkingdoms.local' from its current workgroup 'WORKGROUP' 
with following error message: The specified domain either does not exist or could not be contacted.", "reboot_required": false}`

### Second Run
If i let this run through and retry after it finished i am getting then the error mentioned in the original issue:
`fatal: [srv02]: FAILED! => {"changed": true, "msg": "failed to join domain: Computer 'castelblack' failed to join domain 'north.sevenkingdoms.local' from its current workgroup 'WORKGROUP' 
with following error message: The specified network name is no longer available.", "reboot_required": false}`

My best guess would be that this is due to some smb settings that get changed during the later setup.

### My Workaround:
For me it worked now to **instantly cancel the setup after the first error and retry**. On the second try it went through flawlessly.

**Comment by andrew-gomez** [comment]
Had the same issue, ended up manually adding a DNS entry in /etc/hosts on srv2 and domain joining the host manually. Reran the ansible script and it moved on to the following tasks.

**Comment by charnim** [comment]
None of the solutions above worked, I changed the hardcoded DNS server in srv02 to 192.168.56.10(dc01) instead of 192.168.56.11(which is the dc02) and the computer was able to join.

**Comment by pr0b3r7** [comment]
> Solved mine here by removing other DNS of DC02 NAT interface, so now it has only 127.0.0.1

For me, this error was fixed by setting DC02 as DNS server in SRV02 - after that I was able to manually join SRV02 to the north.sevenkingdoms.local domain using the `Administrator:NgtI75cKV+Pu` credentials

**Comment by Mayfly277** [comment]
i close this issue, i think i have fixed this a while ago. if not the case please reopen :)

**Comment by TheCyberPadawan** [comment]
Hello Mayfly, il y a un tuto pour résoudre ce probleme pour un débutant ? c'est pas super clair pour moi ... merci

**Comment by youyou-pm10** [comment]
I try to reload vagrant, to turn off defender and to enable SMB 1.0/CIFS but all fails.Could you have any ideas?

**Comment by Argonx21** [comment]
> Had the same issue, ended up manually adding a DNS entry for north.sevenkindoms.local in C:\Windows\system32\drives\etc\hosts on srv2 and domain joining the host manually. Reran the ansible script and it moved on to the following tasks.

Can you tell me how you did it?

**Comment by Mayfly277** [comment]
> Hello Mayfly, il y a un tuto pour résoudre ce probleme pour un débutant ? c'est pas super clair pour moi ... merci

it is a dns issue (it's always dns). If you use the v3 version of goad i think i have fixed all the dns issue (at least i hope).
if you don't want to rebuild the lab go to srv02 right clic on the adapter with the local ip and change the dns ipv4 to dc02 ip adress.
